export const blockchains = [
  {
    item: "Aeternity",
    slug: "aeternity",
    icon: "/blockchains/aeternity.svg",
    placeholder: "ak_... address",
    coin: "AE",
  },
  {
    item: "Binance",
    slug: "bsc",
    icon: "/blockchains/binance.svg",
    placeholder: "0x... address",
    coin: "BNB",
  },
  {
    item: "Celo",
    slug: "celo",
    icon: "/blockchains/celo.svg",
    placeholder: "0x... address",
    coin: "CELO",
  },
  {
    item: "Cube",
    slug: "cube",
    icon: "/blockchains/cube.svg",
    placeholder: "0x... address",
    coin: "CUBE",
  },
  {
    item: "Ethereum",
    slug: "ethereum",
    icon: "/blockchains/ethereum.svg",
    placeholder: "0x... or .eth",
    coin: "ETH",
  },
  {
    item: "Evmos",
    slug: "evmos",
    icon: "/blockchains/evmos.svg",
    placeholder: "0x... address",
    coin: "EVMOS",
  },
  {
    item: "Klaytn",
    slug: "klaytn",
    icon: "/blockchains/klaytn.svg",
    placeholder: "0x... address",
    coin: "KLAY",
  },
  {
    item: "Moonbeam",
    slug: "moonbeam",
    icon: "/blockchains/moonbeam.svg",
    placeholder: "0x... address",
    coin: "GLMR",
  },
  {
    item: "Polygon",
    slug: "polygon",
    icon: "/blockchains/polygon.svg",
    placeholder: "0x... address",
    coin: "MATIC",
  },
  {
    item: "Ripple",
    slug: "ripple",
    icon: "/blockchains/ripple.svg",
    placeholder: "r... address",
    coin: "XRP",
  },
  {
    item: "Solana",
    slug: "solana",
    icon: "/blockchains/solana.svg",
    placeholder: "Wallet address",
    coin: "SOL",
  },
  {
    item: "Hedera",
    slug: "hedera",
    icon: "/blockchains/hedera.svg",
    placeholder: "Wallet address",
    coin: "HBAR",
  },
  // {
  //   item: "Celo",
  //   slug: "celo",
  //   icon: "/blockchains/celo.svg",
  //   placeholder: "Address or .sol",
  //   coin: "CELO",
  // },
];
