export const blockchains = [
  {
    item: "Aeternity",
    slug: "aeternity",
    icon: "/blockchains/aeternity.svg",
    placeholder: "ak_... or .chain",
    coin: "AE",
  },
  {
    item: "Binance",
    slug: "bsc",
    icon: "/blockchains/binance.svg",
    placeholder: "0x... or .bnb",
    coin: "BNB",
  },
  {
    item: "Cube",
    slug: "cube",
    icon: "/blockchains/cube.svg",
    placeholder: "0x...",
    coin: "CUBE",
  },
  {
    item: "Ethereum",
    slug: "ethereum",
    icon: "/blockchains/ethereum.svg",
    placeholder: "0x... or .eth",
    coin: "ETH",
  },
  {
    item: "Evmos",
    slug: "evmos",
    icon: "/blockchains/evmos.svg",
    placeholder: "0x or .evns",
    coin: "EVMOS",
  },
  {
    item: "Klaytn",
    slug: "klaytn",
    icon: "/blockchains/klaytn.svg",
    placeholder: "0x.. or .klay",
    coin: "KLAY",
  },
  {
    item: "Moonbeam",
    slug: "moonbeam",
    icon: "/blockchains/moonbeam.svg",
    placeholder: "0x.. or .moon",
    coin: "GLMR",
  },
  {
    item: "Polygon",
    slug: "polygon",
    icon: "/blockchains/polygon.svg",
    placeholder: "0x.. or .poly",
    coin: "MATIC",
  },
  {
    item: "Ripple",
    slug: "ripple",
    icon: "/blockchains/ripple.svg",
    placeholder: "r... address",
    coin: "XRP",
  },
  {
    item: "Solana",
    slug: "solana",
    icon: "/blockchains/solana.svg",
    placeholder: "Address or .sol",
    coin: "SOL",
  },
];
