import {
  blur,
  borders,
  breakpoints,
  colors,
  config,
  fontSizes,
  fontWeights,
  fonts,
  letterSpacings,
  lineHeights,
  radii,
  shadows,
  sizes,
  space,
  styles,
  transition,
  zIndices,
} from "./general";

import { semanticColors } from ".";

import {
  Accordion,
  Alert,
  Avatar,
  Badge,
  Breadcrumb,
  Button,
  Card,
  Checkbox,
  CloseButton,
  Code,
  Container,
  Divider,
  Drawer,
  Editable,
  Form,
  FormError,
  FormLabel,
  Heading,
  Input,
  Kbd,
  Link,
  List,
  Menu,
  Modal,
  NumberInput,
  PinInput,
  Popover,
  Progress,
  Radio,
  Select,
  Skeleton,
  SkipLink,
  Slider,
  Spinner,
  Stat,
  Switch,
  Table,
  Tabs,
  Tag,
  TextArea,
  Tooltip,
} from "./components";

export const theme = {
  blur,
  borders,
  breakpoints,
  colors,
  // components: {
  //   Accordion,
  //   Alert,
  //   Avatar,
  //   Badge,
  //   Breadcrumb,
  //   Button,
  //   Card,
  //   Checkbox,
  //   CloseButton,
  //   Code,
  //   Container,
  //   Divider,
  //   Drawer,
  //   Editable,
  //   Form,
  //   FormError,
  //   FormLabel,
  //   Heading,
  //   Input,
  //   Kbd,
  //   Link,
  //   List,
  //   Menu,
  //   Modal,
  //   NumberInput,
  //   PinInput,
  //   Popover,
  //   Progress,
  //   Radio,
  //   Select,
  //   Skeleton,
  //   SkipLink,
  //   Slider,
  //   Spinner,
  //   Stat,
  //   Switch,
  //   Table,
  //   Tabs,
  //   Tag,
  //   TextArea,
  //   Tooltip,
  // },
  config,
  direction: "ltr",
  fontSizes,
  fontWeights,
  fonts,
  letterSpacings,
  lineHeights,
  radii,
  semanticTokens: {
    colors: {
      "chakra-body-text": {
        _light: "blackAlpha.800",
        _dark: "whiteAlpha.800",
      },
      "chakra-body-bg": {
        _light: "white",
        _dark: "black",
      },
      "chakra-border-color": {
        _light: "gray.200",
        _dark: "gray.800",
      },
      "chakra-subtle-bg": {
        _light: "gray.100",
        _dark: "gray.700",
      },
      "chakra-placeholder-color": {
        _light: "blackAlpha.400",
        _dark: "whiteAlpha.400",
      },
    },
  },
  shadows,
  sizes,
  space,
  styles,
  transition,
  zIndices,
};
