export interface IScoreBlockchain {
  name: string;
  apiSlug: string;
  slug: string;
  group: string;
  nativeCurrency: string;
  addressStartWith: string | null;
  evm: boolean;
  /** Year, month, day */
  genesisDate: Date;
}

export const scoreBlockchainsList: IScoreBlockchain[] = [
  {
    name: "Aeternity",
    apiSlug: "aeternity",
    slug: "aeternity",
    group: "finance",
    nativeCurrency: "ETH",
    addressStartWith: "ak_",
    evm: false,
    genesisDate: new Date("2017-09-02"),
  },
  {
    name: "Aptos",
    apiSlug: "aptos",
    slug: "aptos",
    group: "finance",
    nativeCurrency: "APTOS",
    addressStartWith: "0x",
    evm: true,
    genesisDate: new Date("2022/24/02"),
  },
  {
    name: "Arbitrum One",
    apiSlug: "arbitrumone",
    slug: "arbitrumone",
    group: "finance",
    nativeCurrency: "ETH",
    addressStartWith: "0x",
    evm: true,
    genesisDate: new Date("2021/09/14"),
  },
  {
    name: "Binance",
    apiSlug: "bsc",
    slug: "binance",
    group: "finance",
    nativeCurrency: "BNB",
    addressStartWith: "0x",
    evm: true,
    genesisDate: new Date("2017/07/08"),
  },
  {
    name: "Celo",
    apiSlug: "celo",
    slug: "celo",
    group: "finance",
    nativeCurrency: "CELO",
    addressStartWith: "0x",
    evm: true,
    genesisDate: new Date("2020/05/06"),
  },
  {
    name: "Cube",
    apiSlug: "cube",
    slug: "cube",
    group: "finance",
    nativeCurrency: "CUBE",
    addressStartWith: "0x",
    evm: true,
    genesisDate: new Date("2020/06/09"),
  },
  {
    name: "Ethereum",
    apiSlug: "ethereum",
    slug: "ethereum",
    group: "finance",
    nativeCurrency: "ETH",
    addressStartWith: "0x",
    evm: true,
    genesisDate: new Date("2015/07/30"),
  },
  {
    name: "Evmos",
    apiSlug: "evmos",
    slug: "evmos",
    group: "finance",
    nativeCurrency: "EVMOS",
    addressStartWith: "0x",
    evm: true,
    genesisDate: new Date("2022/05/04"),
  },
  {
    name: "Hedera",
    apiSlug: "hedera",
    slug: "hedera",
    group: "finance",
    nativeCurrency: "HBAR",
    addressStartWith: null,
    evm: false,
    genesisDate: new Date("2018/09/18"),
  },
  {
    name: "Klaytn",
    apiSlug: "klaytn",
    slug: "klaytn",
    group: "finance",
    nativeCurrency: "KLAY",
    addressStartWith: "0x",
    evm: true,
    genesisDate: new Date("2020/03/31"),
  },
  {
    name: "Moonbeam",
    apiSlug: "moonbeam",
    slug: "moonbeam",
    group: "finance",
    nativeCurrency: "GLMR",
    addressStartWith: "0x",
    evm: true,
    genesisDate: new Date("2022/01/11"),
  },
  {
    name: "Polygon",
    apiSlug: "polygon",
    slug: "polygon",
    group: "finance",
    nativeCurrency: "MATIC",
    addressStartWith: "0x",
    evm: true,
    genesisDate: new Date("2091/04/29"),
  },
  {
    name: "Polygon",
    apiSlug: "polygon",
    slug: "polygon",
    group: "eco",
    nativeCurrency: "MATIC",
    addressStartWith: "0x",
    evm: true,
    genesisDate: new Date("2019/04/29"),
  },
  {
    name: "Ripple",
    apiSlug: "ripple",
    slug: "ripple",
    group: "finance",
    nativeCurrency: "XRP",
    addressStartWith: "r",
    evm: false,
    genesisDate: new Date("2013/08/05"),
  },
  {
    name: "Solana",
    apiSlug: "solana",
    slug: "solana",
    group: "finance",
    nativeCurrency: "SOL",
    addressStartWith: null,
    evm: false,
    genesisDate: new Date("2020/04/11"),
  },
  {
    name: "TRON",
    apiSlug: "tron",
    slug: "tron",
    group: "finance",
    nativeCurrency: "TRX",
    addressStartWith: null,
    evm: false,
    genesisDate: new Date("2017/08/28"),
  },
  {
    name: "Trust EVM",
    apiSlug: "trustevm",
    slug: "trustevm",
    group: "finance",
    nativeCurrency: "ETH",
    addressStartWith: "0x",
    evm: true,
    genesisDate: new Date("2022/12/01"),
  },
  {
    name: "Waves",
    apiSlug: "waves",
    slug: "waves",
    group: "finance",
    nativeCurrency: "WAVES",
    addressStartWith: null,
    evm: false,
    genesisDate: new Date("2016/06/12"),
  },
  {
    name: "XDC Network",
    apiSlug: "xdc",
    slug: "xdc",
    group: "finance",
    nativeCurrency: "XDC",
    addressStartWith: "0x",
    evm: true,
    genesisDate: new Date("2018/04/17"),
  },
];
